title: AntiCopyPaster - Summer 2023 Extension Research
description: This site contains the internal information for our Summer 2023 research on the AntiCopyPaster tool.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
